version: "3"
services:
  springboot-assignment:
    container_name: springboot-app
    restart: always
    depends_on:
      - mysqldb
    image: springboot-assignment
    build: .
    ports:
      - 8081:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/test?autoReconnect=true&failOverReadOnly=false&maxReconnects=10
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
    - 3307:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USERNAME: root
